# Generated by Django 4.1.1 on 2022-11-27 21:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_mypost_delete_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyPost',
            new_name='Post',
        ),
    ]
